apiVersion: v1
kind: Service
metadata:
  namespace: maf-analysis
  name: service-farside-data-api
spec:
  selector:
    maf.deployment: farside-data-api
  type: NodePort
  ports:
    - name: http
      port: 9680
      targetPort: 9680
      protocol: TCP
      nodePort: 32721
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: maf-analysis
  labels:
    maf.deployment: farside-data-api
  name: farside-data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      maf.deployment: farside-data-api
  template:
    metadata:
      labels:
        maf.deployment: farside-data-api
    spec:
      nodeSelector:
        nodeType: core
      containers:
        - image: "737281747633.dkr.ecr.us-east-1.amazonaws.com/mesa/farside-data-api:v1.0.1"
          imagePullPolicy: IfNotPresent
          name: farside-data-api
          resources: {}
          securityContext:
            privileged: true
          args:
          - "-listen-address=:9680"
          - "-log-format=Splunk"
          - "-region=us-east-1"
          - "-stack-suffix=qa1"
      restartPolicy: Always